# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cbf6540638f98b11e121c1d5037f34e885dfbd1bb2998970d540efff50fa7c8048e45f9f27be3689c85de02ec8b696e0d43bd61a757e93dd8e1c8477cb532b6

test:
  secret_key_base: 6a1f2bae215a4feb0c6bdbf7f3a85143c7353a568ce0d09e44f45ea0b3a976540f94d1eb40cc8142d9691f6ec1f09e90147bf90afb854d82e8c4812f27f6c845

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
